import { useState, type ReactNode } from 'react';
import RegistrationVerification from './RegistrationVerification';

export default function PortalEntry({type,mobile,children}:{type:'organization'|'business';mobile:boolean;children:ReactNode}) {
  const [screen,setScreen]=useState<'login'|'register'|'dashboard'>('login');
  const [email,setEmail]=useState('');
  const [password,setPassword]=useState('');
  const label=type==='organization'?'Organization':'Local Business';
  if(screen==='dashboard') return <div className="h-full flex flex-col min-h-0"><div className="bg-[#071426] text-slate-400 px-4 py-2 text-[10px] flex justify-between gap-2"><span>Demo account · verification simulated</span><button className="text-amber-400" onClick={()=>{setPassword('');setScreen('login')}}>Back to login</button></div><div className="flex-1 min-h-0" onClickCapture={e=>{const button=(e.target as HTMLElement).closest("button");if(button?.textContent?.trim()==="Sign out"){setPassword("");setScreen("login")}}}>{children}</div></div>;
  if(screen==='register') return <RegistrationVerification type={type} mobile={mobile} onCancel={()=>setScreen('login')} onComplete={()=>setScreen('dashboard')}/>;
  return <div className={`h-full overflow-y-auto bg-[#020b18] text-white ${mobile?'px-5 pt-16 pb-10':'p-10 flex items-center justify-center'}`}><div className="w-full max-w-md mx-auto"><div className="text-amber-400 text-sm font-black">OrgConnect</div><h1 className="text-2xl font-black mt-6">Welcome back</h1><p className="text-slate-400 text-xs mt-2">Log in to your {label.toLowerCase()} account.</p><form className="space-y-4 mt-7" noValidate onSubmit={e=>{e.preventDefault();setScreen('dashboard')}}><label className="block text-xs">Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" className="mt-2 block w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3 outline-none focus:border-amber-400"/></label><label className="block text-xs">Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" className="mt-2 block w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3 outline-none focus:border-amber-400"/></label><button className="w-full py-3 rounded-xl bg-amber-400 text-[#020b18] font-black text-sm">Log in</button></form><p className="text-xs text-slate-400 text-center mt-5">Haven’t registered yet? <button onClick={()=>setScreen('register')} className="text-amber-400 font-bold">Sign up</button></p><div className="mt-7 border border-white/10 rounded-xl p-4"><p className="text-slate-400 text-[11px] leading-relaxed">Interactive prototype: click Log in to proceed, or choose Sign up to preview registration. All fields are optional.</p><button onClick={()=>setScreen('dashboard')} className="text-amber-400 text-xs font-bold mt-3">Try demo account</button></div></div></div>;
}
